# Generated by Django 4.2.1 on 2023-09-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_installation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='installation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
