# Generated by Django 4.2.5 on 2023-09-15 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('registration', '0005_farmer_delete_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Farmer',
            new_name='CustomUser',
        ),
    ]
