# Generated by Django 3.2.12 on 2023-09-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowrate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name_plural': 'devices'},
        ),
    ]
