# Generated by Django 3.2.12 on 2023-09-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowrate', '0002_alter_device_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowrate',
            options={'verbose_name_plural': 'flowrates'},
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
