# Generated by Django 4.2.5 on 2023-09-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowrate', '0003_auto_20230912_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
        migrations.AddField(
            model_name='device',
            name='device_owner',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
