# Generated by Django 4.2.5 on 2023-09-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowrate', '0004_remove_device_name_device_device_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_owner',
            field=models.CharField(max_length=50),
        ),
    ]
